version: "3.8"

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # MinIO API Port
      - "9001:9001" # MinIO Console Port
    environment:
      # CHANGE THESE SECRETS FOR PRODUCTION!
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data # Persist data locally

volumes:
  minio_data:
